version: "3.9"

services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: organization-aw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    restart: on-failure